[package]
name = "zn-client"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.11.0"
serde = {version = "1", features=["derive"] }
serde_json = "1.0.44"
stdweb = "0.4.20"
wasm-bindgen = "^0.2"
failure = "0.1.6"
zn-core = { path = "../core" }
