[package]
name = "zn-core"
version = "0.0.1"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
bincode = "1.2.1"
